security:
    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'email'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            logout:
                path: app_logout
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 12

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
